name: Run Jupyter Notebook

on: [push]

jobs:
  run_notebook:
    runs-on: ubuntu-latest

    env:
      ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Jupyter Notebook
        run: |
          set -e
          jupyter nbconvert --to notebook --execute Stock_Market_Anomaly_Detection.ipynb --output Anomaly_Result_Notebook.ipynb

      - name: Upload result notebook
        uses: actions/upload-artifact@v3
        with:
          name: result-notebook
          path: result_notebook.ipynb
